var annotated_dup =
[
    [ "AirMaterial", "class_air_material.html", "class_air_material" ],
    [ "BadMapObjectException", "class_bad_map_object_exception.html", "class_bad_map_object_exception" ],
    [ "BadNumberOfInputException", "class_bad_number_of_input_exception.html", "class_bad_number_of_input_exception" ],
    [ "CaseMap", "class_case_map.html", "class_case_map" ],
    [ "Controller", "class_controller.html", "class_controller" ],
    [ "Creature", "class_creature.html", "class_creature" ],
    [ "DirtMaterial", "class_dirt_material.html", "class_dirt_material" ],
    [ "EventListNotCreatedException", "class_event_list_not_created_exception.html", "class_event_list_not_created_exception" ],
    [ "Evolution", "class_evolution.html", "class_evolution" ],
    [ "exception", "classexception.html", null ],
    [ "FoodMaterial", "class_food_material.html", "class_food_material" ],
    [ "Graphic", "class_graphic.html", "class_graphic" ],
    [ "Map", "class_map.html", "class_map" ],
    [ "MapObjective", "class_map_objective.html", "class_map_objective" ],
    [ "MapProc", "class_map_proc.html", "class_map_proc" ],
    [ "Material", "class_material.html", "class_material" ],
    [ "Neuron", "class_neuron.html", "class_neuron" ],
    [ "NeuronLayer", "class_neuron_layer.html", "class_neuron_layer" ],
    [ "NeuronNetwork", "class_neuron_network.html", "class_neuron_network" ],
    [ "NotEnoughBrainException", "class_not_enough_brain_exception.html", "class_not_enough_brain_exception" ],
    [ "NotEnoughCreatureException", "class_not_enough_creature_exception.html", "class_not_enough_creature_exception" ],
    [ "NotSameStructException", "class_not_same_struct_exception.html", "class_not_same_struct_exception" ],
    [ "ObjectFood", "class_object_food.html", "class_object_food" ],
    [ "ObjectMap", "class_object_map.html", "class_object_map" ],
    [ "ObjectWater", "class_object_water.html", "class_object_water" ],
    [ "Position", "class_position.html", "class_position" ],
    [ "WaterMaterial", "class_water_material.html", "class_water_material" ],
    [ "WindowNotCreatedException", "class_window_not_created_exception.html", "class_window_not_created_exception" ]
];